id: P001791
initial_creation_type: ocr
source_metadata:
  id: bdr:W679
  title: ཟབ་མོ་ནང་དོན་རྩ་བ
  author: ''
  volumes:
    38c3165357f24a96b95682b9a6fe4bd5:
      image_group_id: I1701
      title: ''
      volume_number: 1
      total_pages: 79
      base_file: v001.txt
