id: IA6E4AEFE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T20:48:27+00:00'
last_modified: '2022-06-07T15:10:32.544213+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W679
  title: ཟབ་མོ་ནང་དོན་རྩ་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5D8C:
      image_group_id: I1701
      title: ''
      total_pages: 79
      order: 1
      base_file: 5D8C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
